//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/seriesDataSet.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/seriesDataSet.xsd", IsNullable=false)]
public partial class seriesDataSet {
    
    private seriesDataSetSeries_info[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("series_info")]
    public seriesDataSetSeries_info[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/seriesDataSet.xsd")]
public partial class seriesDataSetSeries_info {
    
    private int idField;
    
    private System.DateTime fechaField;
    
    private string serieField;
    
    private string idiomaField;
    
    private bool subtituloField;
    
    private int temporadaField;
    
    private int episodiosField;
    
    private string grupoField;
    
    private string enlaceField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime fecha {
        get {
            return this.fechaField;
        }
        set {
            this.fechaField = value;
        }
    }
    
    /// <remarks/>
    public string serie {
        get {
            return this.serieField;
        }
        set {
            this.serieField = value;
        }
    }
    
    /// <remarks/>
    public string idioma {
        get {
            return this.idiomaField;
        }
        set {
            this.idiomaField = value;
        }
    }
    
    /// <remarks/>
    public bool subtitulo {
        get {
            return this.subtituloField;
        }
        set {
            this.subtituloField = value;
        }
    }
    
    /// <remarks/>
    public int temporada {
        get {
            return this.temporadaField;
        }
        set {
            this.temporadaField = value;
        }
    }
    
    /// <remarks/>
    public int episodios {
        get {
            return this.episodiosField;
        }
        set {
            this.episodiosField = value;
        }
    }
    
    /// <remarks/>
    public string grupo {
        get {
            return this.grupoField;
        }
        set {
            this.grupoField = value;
        }
    }
    
    /// <remarks/>
    public string enlace {
        get {
            return this.enlaceField;
        }
        set {
            this.enlaceField = value;
        }
    }
}
